apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: control-plane
    app: metis-api
  name: metis-api
  namespace: kube-system
spec:
  selector:
    matchLabels:
      tier: control-plane
      app: metis-api
  replicas: 1
  template:
    metadata:
      labels:
        tier: control-plane
        app: metis-api
    spec:
      serviceAccountName: my-scheduler
      containers:
        - name: metis-api
          image: jongbeomlee/metis-api:latest
          # imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.1"
          securityContext:
            privileged: false
      hostNetwork: false
      hostPID: false
---
apiVersion: v1
kind: Service
metadata:
  name: metis-api-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: metis-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster
