apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-a
  template:
    metadata:
      labels:
        app: pod-a
    spec:
      schedulerName: my-scheduler
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-b-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pod-b
  template:
    metadata:
      labels:
        app: pod-b
    spec:
      schedulerName: my-scheduler
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-c-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-c
  template:
    metadata:
      labels:
        app: pod-c
    spec:
      schedulerName: my-scheduler
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "256Mi"
              cpu: "512m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-d-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-d
  template:
    metadata:
      labels:
        app: pod-d
    spec:
      schedulerName: my-scheduler
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "256Mi"
              cpu: "512m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-e-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-e
  template:
    metadata:
      labels:
        app: pod-e
    spec:
      schedulerName: my-scheduler
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"
