apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler
  labels:
    name: multischeduler-example
spec:
  schedulerName: my-scheduler
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler-2
  labels:
    name: multischeduler-example
spec:
  schedulerName: my-scheduler
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler-3
  labels:
    name: multischeduler-example
spec:
  schedulerName: my-scheduler
  containers:
    - name: nginx
      image: nginx
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: nginx-statefulset
# spec:
#   serviceName: "nginx"
#   replicas: 3
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       schedulerName: my-scheduler
#       containers:
#         - name: nginx
#           image: nginx:latest
#           ports:
#             - containerPort: 80
#   volumeClaimTemplates:
#     - metadata:
#         name: nginx-persistent-storage
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 500Mi
