kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    #    kubeadmConfigPatches:
    #    - |
    #      kind: InitConfiguration
    #      nodeRegistration:
    #        kubeletExtraArgs:
    #          register-with-taints: "node-role.kubernetes.io/control-plane=:NoSchedule"
  - role: worker
  - role: worker
  - role: worker
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "istio-control-plane=true"
          register-with-taints: "dedicated=istio:NoSchedule"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "monitoring=true"
          register-with-taints: "dedicated=monitoring:NoSchedule"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "dedicated=loadgenerator"
          register-with-taints: "dedicated=loadgenerator:NoSchedule"
